apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  namespace: labels-lab
  labels:
    app: frontend
    environment: production
    tier: web

spec:
  containers:
    - name: nginx
      image: nginx:stable

---
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  namespace: labels-lab
  labels:
    app: backend
    environment: production
    tier: api

spec:
  containers:
    - name: nginx
      image: nginx:stable

---
apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  namespace: labels-lab
  labels:
    app: backend
    environment: development
    tier: worker

spec:
  containers:
    - name: nginx
      image: nginx:stable
