apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: selector-demo
spec:
  selector:
    app: backend-service

  ports:
    - name: backend-service
      protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP
