apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  namespace: selector-demo

spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
        environment: production

    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
